feat: Support exteneded interface  parameters
fossamagna/google-script-dts-generator pull request #194
Opened 2023-06-27 03:23 UTC by mato533

Changed to be able to output Type definitions for extended interfaces.

Remacks:
[dts-dom](https://github.com/RyanCavanaugh/dts-dom)@v3.7.0 has the [bug](https://github.com/RyanCavanaugh/dts-dom/issues/88) that is related to print extends statements.
So avoid this bug, use [dts-dom](https://github.com/RyanCavanaugh/dts-dom)@v3.6.0.

Refs: #193

2023-06-29 14:23 UTC, fossamagna requested changes
Hey @mato533 thanks for the contribution! Functionally this change looks good to me, a small nits to address.

2023-06-29 14:23 UTC, fossamagna commented on package.json
> +    "dts-dom": "~3.6.0",
Please update `yarn.lock` too.

2023-06-29 22:10 UTC, mato533 commented
Thank you for review. I missed the updating the yarn.lock file. So I Fixed it.

2023-06-29 22:23 UTC, mato533 commented on package.json
> +    "dts-dom": "~3.6.0",
Thx! I have pushed it.

2023-06-30 00:26 UTC, fossamagna approved these changes

2023-06-30 00:26 UTC, merged